version: '3'
services:
  drupal:
    image: jdgp77/drupalcamp:v1.0.0
    volumes:
      - ./drupal:/var/www/html
    env_file:
      - ./docker.env
    ports:
      - "10080:80"
      - "10022:22"
    working_dir: /var/www/html
    tty: true
    command: apachectl -D FOREGROUND
  db:
    image: mysql:8.0
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
      - ./db/datalib:/var/lib/mysql
    env_file:
      - ./docker.env
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  pma:
    image: phpmyadmin/phpmyadmin:edge
    env_file:
      - ./docker.env
    ports:
     - "18080:80"
  react:
    image: node:10.19.0-jessie
    working_dir: /app
    volumes:
      - ./react-app:/app
    ports:
     - "13000:3000"
    tty: true
